urls.py
import settings
from django.conf.urls.defaults import *
import domesday.domes.forms as domes_forms
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views as auth_views
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Home page
    url(r'^$', 'domes.views.homepage', name="home"),
    # Map
    url(r'map/$', 'domes.views.map', name="map"),
    # Places
    url(r'^county/$', 'domes.views.all_counties', name="counties"),
    url(r'^county/(?P<county_slug>.+)/$', 'domes.views.county', name="county"),
    url(r'^place/$', 'domes.views.all_places', name="all_places"),
    url(r'^place/(?P<grid>[A-Za-z0-9]+)/(?P<vill_slug>.+)/$', 'domes.views.place', name="place"),
    url(r'^hundred/(?P<hundred_slug>.+)/$', 'domes.views.hundred', name="hundred"),
    # People
    url(r'^name/$', 'domes.views.all_names', name="all_names"),
    url(r'^name/(?P<namesidx>[0-9]+)/(?P<name_slug>.+)/$', 'domes.views.name', name="name"),
    # Images
    url(r'^image/$', 'domes.views.all_images', name="all_images"),
    url(r'^image/(?P<county>[A-Za-z]+)/(?P<number>[0-9]+)/$', 'domes.views.image', name="image"),
    # Book
    url(r'^text/$', 'domes.views.text', name="text"),
    url(r'^book/$', 'domes.views.book', name="book"),
    # Translation & crowdsourcing
    url(r'^translate/$', 'domes.views.translate', name="translate"),
    url(r'^translate/(?P<county>[a-z]+)/$', 'domes.views.translate', name="translate_county"), 
    url(r'^translate/(?P<structidx>[0-9]+)/$', 'domes.views.crowdsource', name="crowdsource"), 
    url(r'^translated/$', 'domes.views.translated', name="translated"),
    # Stats
    url(r'^stats/$', 'domes.views.stats', name="stats"), 
    # FAQ and to-do list
    #url(r'^forum/$', 'domes.views.forum', name="forum"),
    url(r'^about/$', 'domes.views.about', name="about"),
    url(r'^help/$', 'domes.views.help', name="help"),
    url(r'^todo/$', 'domes.views.todo', name="todo"),
    # Search page
    url(r'^search/$', 'domes.views.search', name="search"),
    # Comments
    (r'^comments/', include('django.contrib.comments.urls')),
    # API
    url(r'^api/$', 'domes.views.api', name="api"),
    url(r'^markers_within_bounds/$', 'domes.views.markers_within_bounds', name="markers_within_bounds"), 
    url(r'^all_markers/$', 'domes.views.all_places_json', name="all_markers"),   
    # Contact form
    (r'^contact/', include('contact_form.urls')),
    # Json files (used for autocomplete)
    url(r'^all_places_json/$', 'domes.views.all_places_json', name="all_places_json"),
    # Photo-tagging files
    url(r'^crop/$', 'domes.views.crop_all', name="crop_all"),
    url(r'^crop/(?P<file_id>[A-Za-z0-9_]+)/$', 'domes.views.crop_file', name="crop_file"), 
    url(r'^crop_results/$', 'domes.views.crop_results', name="crop_results"), 
    url(r'^load_tags/$', 'domes.views.load_tags', name="load_tags"), 
    url(r'^save_tags/$', 'domes.views.save_tags', name="save_tags"), 
    url(r'^delete_tags/$', 'domes.views.delete_tags', name="delete_tags"), 
    # static files of various kinds
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/media/images/favicon.ico'}),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Static media server for local dev
    url(r'^media/(?P<path>.*)$',       'django.views.static.serve', {'document_root': settings.MEDIA_DIR, 'show_indexes':True}),
    #(r'^forum/', include('snapboard.urls')),
    #(r'^accounts/login/$', auth_views.login, {'template_name': 'forum/signin.html'}, 'auth_login'),
    #(r'^accounts/logout/$', auth_views.logout, {'template_name': 'forum/signout.html'}, 'auth_logout'),
    #(r'^accounts/register/$',register, {'form_class': RegistrationForm, 'profile_callback':UserProfile.objects.profile_callback},name = 'registration_register'),
    (r'^accounts/', include('registration.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^admin/(.*)', admin.site.root),
)

domes/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import User

####################################
# Place-related tables
####################################
class County(models.Model):
    short_code = models.CharField(max_length=3, primary_key=True)
    name = models.CharField(max_length=100)
    name_slug = models.SlugField()
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('domes.views.county', (), {
            'county_slug': self.name_slug })
    
class Area(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    name_slug = models.SlugField()
    def __unicode__(self):
        return self.name
        
class Hundred(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    name_slug = models.SlugField()
    status = models.CharField(max_length=100, null=True, blank=True)
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('domes.views.hundred', (), {
            'hundred_slug': self.name_slug })
            
# Place. From PlacesForAHRC.txt
class Place(models.Model):
    id = models.IntegerField(primary_key=True) 
    county = models.ManyToManyField(County,related_name='county')
    area = models.ManyToManyField(Area,related_name='area')
    hundred = models.ForeignKey(Hundred, null=True)
    phillimore = models.CharField(max_length=300, null=True, blank=True)
    vill = models.CharField(max_length=300)
    vill_slug = models.SlugField()
    xrefs = models.CharField(max_length=300, null=True, blank=True)
    grid = models.CharField(max_length=120, null=True, blank=True) # OS grid ref
    os_codes = models.CharField(max_length=120, null=True, blank=True) # 'uncertain', etc
    location = models.PointField(null=True, blank=True)
    objects = models.GeoManager()
    status = models.CharField(max_length=100, null=True, blank=True)
    def __unicode__(self):
        return self.vill
    class Meta:
        ordering = ('hundred', 'vill')
    @property
    def value(self):
        manors = Manor.objects.filter(place__id=self.id)
        total = {}
        for manor in manors:
            if not manor.geld:
                 continue
            else:
                 manor_geld = manor.geld / manor.place.count()
            if manor.gcode in total.keys():
                 total[manor.gcode] += manor_geld
            else:
                 total[manor.gcode] = manor_geld
        return total
    @property
    def raw_value(self):
        manors = Manor.objects.filter(place__id=self.id)
        total = 0.0
        for manor in manors:
            manor_total = 0.0
            if manor.geld:
                manor_total += manor.geld
            manor_total = manor_total / manor.place.count()
            total += manor_total           
        return total
    @property
    def population(self):
        manors = Manor.objects.filter(place__id=self.id)
        people = 0.0
        for manor in manors:
            manor_people = 0.0
            people_types = [manor.villagers, manor.smallholders, manor.slaves,\
                        manor.femaleslaves, manor.freemen, manor.free2men,\
                        manor.priests, manor.cottagers, manor.otherpop,\
                        manor.miscpop, manor.burgesses]
            for p in people_types: 
                if p: manor_people += p
            manor_people = manor_people / manor.place.count()
            people += manor_people
        return people 
    @models.permalink
    def get_absolute_url(self):
        return ('domes.views.place', (), {
            'grid': self.grid,
            'vill_slug': self.vill_slug })
    
####################################
# People-related tables
####################################

# People. From UniqueNames.txt, generated from NamesForAHRC.txt
class Person(models.Model):
    namesidx = models.IntegerField(primary_key=True, verbose_name="ID") # these map to LordIdx etc
    name = models.CharField(max_length=300, verbose_name="Name")     
    name_slug = models.SlugField()        
    namecode = models.CharField(max_length=5, null=True, blank=True, verbose_name="Name code")  
    gendercode = models.CharField(max_length=10, null=True, blank=True, verbose_name="Gender code")  
    churchcode = models.CharField(max_length=100, null=True, blank=True, verbose_name="Church code")  
    xrefs = models.CharField(max_length=300, null=True, blank=True, verbose_name="Cross-refs")
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('domes.views.name', (), {
            'namesidx': self.namesidx,
            'name_slug': self.name_slug })

####################################
# Manor-related tables
####################################
# Manors - a reference to a place in a Domesday entry.
# Everything hangs off this. From ManorsForAHRC.txt
# But never exposed per se in front-end. 
class Manor(models.Model):
    structidx = models.IntegerField(primary_key=True)  
    place = models.ManyToManyField(Place, null=True, related_name="manors")
    county = models.ForeignKey(County)  
    phillimore = models.CharField(max_length=100, null=True, blank=True, verbose_name="Phillimore") 
    headofmanor = models.CharField(max_length=100, null=True, blank=True, verbose_name="Head of manor [manorial centre of group, used for aggregating data]")
    duplicates = models.CharField(max_length=100, null=True, blank=True, verbose_name="Duplicates [code for entry duplicated in whole or in part elsewhere]")   
    subholdings = models.CharField(max_length=100, null=True, blank=True, verbose_name="Subholdings [subholdings whose data is aggregated with manorial totals (Y)]")   
    notes = models.CharField(max_length=400, null=True, blank=True, verbose_name="Notes [notes on problems with the data]")
    waste = models.CharField(max_length=100, null=True, blank=True, verbose_name="Waste [coded form of the formulae used to record waste]") 
    waste66 = models.CharField(max_length=100, null=True, blank=True, verbose_name="Waste in 1066 [code for recorded waste for 1066: see Coding]")  
    wasteqr = models.CharField(max_length=100, null=True, blank=True, verbose_name="Waste circa 1070 [code for recorded waste, circa 1070: see Coding]")    
    waste86 = models.CharField(max_length=100, null=True, blank=True, verbose_name="Waste circa 1086 [code for recorded waste for 1086: see Coding]")
    geld = models.FloatField(null=True, blank=True, verbose_name="Geld [units liable for taxation and other public services in 1066 and 1086]")  
    gcode = models.CharField(max_length=100, null=True, blank=True, verbose_name="Gcode [code for variations in formulae in recording tax units]")  
    villtax = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Villtax [payment by vill when geld on the Hundred is 20 shillings (in old pence): Little Domesday on]") 
    taxedon = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Taxed on [assessment units on which tax is actually paid]")
    value86 = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Value in 1086 [value of the holding to its lord in 1086]")  
    value66 = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Value in 1066 [value of the holding to its lord in 1066]")  
    valueqr = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Value circa 1070  [value of the holding to its lord, circa 1070")   
    value_string = models.CharField(max_length=100, null=True, blank=True, verbose_name="Values [standardised form of the formulae used to record values: see Coding ]")    
    render = models.CharField(max_length=100, null=True, blank=True, verbose_name="Renders in addition [payment over and above the stated value of the holding]")   
    lordsland = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Lords land [tax units on the lord's demesne: 'lordship hides']") 
    newland = models.FloatField(max_length=100, null=True, blank=True, verbose_name="New land [additional, unassessed carucates or hides, often described as 'inland' or as carucates in non-carucated areas]")  
    ploughlands = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Ploughlands ['Land for' so many ploughs, often interpreted as the area of arable land, sometimes as a new tax assessment]") 
    pcode = models.CharField(max_length=100, null=True, blank=True, verbose_name="Code [code for variations in formulae in recording ploughland data: see Coding]") 
    lordsploughs = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Lords' ploughs [number of ploughteams attributed to the lord of the manor, the teams assumed to comprise 8 oxen]") 
    mensploughs = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Mens' ploughs [number of ploughteams attributed to the men on the manor, the teams assumed to comprise 8 oxen]")    
    totalploughs = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Total ploughs [total number of ploughteams attributed to the holding]")    
    lordsploughspossible = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Lords' ploughs possible [additional number of lord's ploughteams needed to bring the estate to full working capacity]")    
    mensploughspossible = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Mens' ploughs possible [additional number of men's ploughteams needed to bring the estate to full working capacity]")   
    totalploughspossible = models.FloatField(max_length=100, null=True, blank=True, verbose_name="Total ploughs possible [total number of additional ploughteams needed to bring the estate to full working capacity]")   

domes/forms.py
from django import forms
from django.forms import ModelForm
from domes.models import EmailSignup

class EmailSignupForm(ModelForm):
    class Meta:
        model = EmailSignup

class TranslateForm(forms.Form):
    transcription = forms.CharField(widget=forms.Textarea, min_length=5)

templates/domes/all_places.html
{% extends "domes/base.html" %}

{% block title %}Places{% endblock %}
{% block description %}All places listed in Domesday Book{% endblock %}
{% block nav-class %}nav-places{% endblock %}

{% block content %}

<div class="page_title">
<h1>Places</h1>
</div>

<div class="content">

<p>Hopefully this will get more useful soon.</p>

<!-- A-Z tab -->
	<div class="atozContainer"> 
			<ul class="atoz"> 
				<li ><a href="?indexChar=A">A</a></li> 
				<li ><a href="?indexChar=B">B</a></li> 
				<li ><a href="?indexChar=C">C</a></li> 
				<li ><a href="?indexChar=D">D</a></li> 
				<li ><a href="?indexChar=E">E</a></li>
				<li ><a href="?indexChar=F">F</a></li> 
				<li ><a href="?indexChar=G">G</a></li> 
				<li ><a href="?indexChar=H">H</a></li> 
				<li ><a href="?indexChar=I">I</a></li> 
				<li ><a href="?indexChar=J">J</a></li> 
				<li ><a href="?indexChar=K">K</a></li> 
				<li ><a href="?indexChar=L">L</a></li> 
				<li ><a href="?indexChar=M">M</a></li> 
				<li ><a href="?indexChar=N">N</a></li> 
				<li ><a href="?indexChar=O">O</a></li>
				<li ><a href="?indexChar=P">P</a></li> 
				<li ><a href="?indexChar=Q">Q</a></li> 
				<li ><a href="?indexChar=R">R</a></li> 
				<li ><a href="?indexChar=S">S</a></li> 
				<li ><a href="?indexChar=T">T</a></li> 
				<li ><a href="?indexChar=U">U</a></li> 
				<li ><a href="?indexChar=V">V</a></li> 									
				<li ><a href="?indexChar=W">W</a></li> 
				<li ><a href="?indexChar=Y">Y</a></li> 
				<li ><a href="?indexChar=Z">Z</a></li> 
		</ul> 
	</div>
<div style="clear: both;"></div>

<ul>
{% for place in places %}
<li><a href="{{ place.get_absolute_url }}">
{{ place.vill }}</a>,
{% for county in place.county.all %}{{ county }} {% endfor %}</li>
{% endfor %}
</ul>

</div>
<div style="clear: both;"></div>
{% endblock %}

templates/domes/base.html
<!DOCTYPE html>
	<html lang="en">
	<head>
	<meta charset="utf-8" />
	<title>{% block title %}{% endblock %} | Domesday Book</title>
	<meta name="description" content="{% block description %}{% endblock %}" />
	<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/domesday.css" />
    <script src="http://maps.google.com/maps/api/js?sensor=false&amp;region=GB&amp;key={{ MAPS_API_KEY }}" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/markerclusterer.js"></script>    
	<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.corner.js"></script>     		                                
	<script type="text/javascript" src="{{ MEDIA_URL }}js/domesday.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
		jQuery(function($){
			if (!("autofocus" in document.createElement("input"))) {
		      $('#geo').focus();
		    }
		});

	});
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-20487731-1']);
	  _gaq.push(['_trackPageview']);
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
    </head>

	<body id="{% block nav-class %}{% endblock %}">

	<!-- banner --> 
	<!--  <div class="banner">
	<span id="login">
    {% if user.is_authenticated %}
		 signed in as <a href="{% url profiles_profile_detail user %}">{{user}}</a> 
		 ({{ user.englishtranslation_set.count }} 
		    translation{{ user.englishtranslation_set.count|pluralize }})
		 <a href="{% url auth_logout %}?next_page=/">log out</a>
		{% else %}
		<a href="{% url auth_login %}">log in</a> or <a href="">register</a>
		{% endif %}
	</span>
	 Help <a href="{% url translate %}">translate</a> Domesday Book!
	</div> -->
	
	<!-- header -->
	<header>
	<div id="divHeader"> 
	<!-- logo & title -->
	<div id="divLogo">
	<p><a href="{% url home %}" title="Home">
	<img id="logo_image" src="{{ MEDIA_URL }}images/lion1.gif" alt="Medieval lion logo" 
	    width=50 height=50>Domesday Map</a></p>
	<span id="subtitle">The first online copy of Domesday Book of 1086</span>
	</div>
	
	<!-- main navigation menu -->
	<div id="divMenu">
	<ul>
	<li id="nav-places"><a href="{% url all_places %}">Places</a></li>❧
	<li id="nav-people"><a href="{% url all_names %}">Names</a></li>❧
	<li id="nav-stats"><a href="{% url stats %}">Statistics</a></li> <!--❧
	<li id="nav-translate"><a href="{% url translate %}">Translate</a></li> -->
	</ul>
	{% if not no_search_form %}
	<!-- search form -->
	<form name="f" action="/search/" method="get" id="search_form">
	<small>
	Find Domesday places near:&nbsp;
	<input type="search" id="geo" name="geo" size="20" autofocus /><input type="submit" value="Go"> 
	</small>
	</form>
	{% endif %}
	</div><!-- /divMenu -->
    </div><!-- /divHeader -->
	</header>

    <!-- body of page -->
	<div id="divPage">
	
	<!-- error messages -->	
	<div id="divErrors">		    
	</div>
	
	<!-- central content -->	
	<div id="divContent">
	{% block content %}{% endblock %}
	</div>	
    </div><!-- divPage -->

	<!-- footer -->
	<footer>
	<div id="divFooter">
	<div id="divCopyright">
	 <a href="{% url about %}">About</a></li> ❧ <a href="/contact">Contact</a> ❧  <a href="{% url api %}">API</a> ❧ 
	Site by <a href="http://www.twitter.com/darkgreener">Anna Powell-Smith</a>. Domesday data created by <a href="/about#data">Professor John Palmer, University of Hull</a>.
	</div>
	</div>
	</footer>

	</body>
</html>

templates/domes/crop.html
{% extends "domes/base.html" %}
{% block nav-class %}nav-about{% endblock %}
{% block title %}Crop{% endblock %}
{% block description %}Cropping images with jQuery{% endblock %}

{% block content %}

<div class="page_title">
<h1>Cropping Images - Test</h1>
<p>This page has {{ images_markup.count }} tag{{ images_markup.count|pluralize}}. 
{% if images_markup.count %}
Mouseover the image to see all tags.
{% endif %}</p>
<ol>
<li>To add more tags, select an area of the image with the mouse, then enter the structidx (this must be a number) in the popup box.</li>
<li>If you enter a structidx that does not exist, you will see an error message and the tag will not be saved.</li>
<li>To delete a tag entered by mistake, double-click on the tag.</li>
</ol>
</div>

<div class="content" style="min-height: 800px;">

<div class="photo-column">
  <div class="photo-container">
		<img id="{{ image.county.short_code.title }}_{{ image.filename }}" 
		src="{{MEDIA_URL}}images/{{ image.county.short_code.title }}/{{ image.filename }}"
	 style="border: 1px solid black;" alt="" width="{{ image_width }}" />
  </div>
</div>

</div>

<div style="clear: both;"></div>


<script src="{{MEDIA_URL}}js/jquery.phototagger.js"></script>
<script language="Javascript">
	$(document).ready(function() {
			// Set up the photo tagger.
			$( "div.photo-container" ).photoTagger({
				// The API urls.
				loadURL: "/load_tags/",
				saveURL: "/save_tags/",
				deleteURL: "/delete_tags/",		
		});
	});
</script>

{% endblock %}

templates/domes/crop_files.html
{% extends "domes/base.html" %}
{% block nav-class %}nav-about{% endblock %}
{% block title %}Files for Cropping{% endblock %}
{% block description %}Files for JP to edit{% endblock %}

{% block content %}
<div class="page_title">
<h1>Files for Cropping</h1>
</div>

<div class="content">

<p>Download <a href='{% url crop_results %}'>a .csv file with all coordinates</a>.</p>

<h3>Essex</h3>
<ul>
{% for file in essex_files %}
<li><a href="{{ file.get_absolute_url }}">{{ file }}</a>:
{{ file.image_set.count }} tag{{ file.image_set.count|pluralize }}
{% if file.image_set.count > 0 %}- 
{% for image in file.image_set.all %}
{{ image.manor.structidx }}{% if not forloop.last %}, {% endif %}
{% endfor %}
{% endif %}
</li>
{% endfor %}
</ul>

<h3>Norfolk</h3>
<ul>
{% for file in norfolk_files %}
<li><a href="{{ file.get_absolute_url }}">{{ file }}</a> ({{ file.image_set.count }} tags)</li>
{% endfor %}
</ul>

<h3>Suffolk</h3>
<ul>
{% for file in suffolk_files %}
<li><a href="{{ file.get_absolute_url }}">{{ file }}</a> ({{ file.image_set.count }} tags)</li>
{% endfor %}
</ul>

</div>
<div style="clear: both;"></div>
{% endblock %}

templates/domes/forum.html
{% extends "domes/base.html" %}

{% block title %}Forum{% endblock %}

{% block content %}
<div class="page_title">
<h1>Forum</h1>
</div>

<div class="content">

<p>TBA</p>

</div>

<div style="clear: both;"></div>
{% endblock %}

templates/domes/hundred.html
{% extends "domes/base.html" %}

{% block title %}Hundred of {{ hundred.name }}{% endblock %}
{% block description %}The hundred of {{ hundred.name }} in Domesday Book{% endblock %}
{% block nav-class %}nav-places{% endblock %}
{% block content %}

<div class="page_title">
<h1>Hundred: {{ hundred.name }}</h1>
</div>

<div class="content">

<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.js" ></script> 
<script type="text/javascript" src="{{ MEDIA_URL }}js/tablesorter.js" ></script>

<script type="text/javascript">
$(function() 
    { 
        $("#statsTable").tablesorter({ 
		        headers: { 0: { sorter:'text' } , 
		                   1: { sorter:'digit' } ,
		                   2: { sorter:'digit' } 
		                 } , 
		         sortList: [[2,1]] 
		    });
    } 
)
</script>

<div id="divMap">
<div id="map_canvas" style="width:400px; height:400px;"></div>
</div>
</div>

{% if hundred.status %}
<ul>
<li><span id="identification" class="section_title tooltip">Lost</span>: {{ hundred.status }}</li>
</ul>
{% endif %}

<p>There were {{ places.count }} places in the hundred of <strong>{{ hundred.name }}</strong> in Domesday Book.</p>

<table id="statsTable" class="tablesorter" >
<thead><tr>
<th>Name</th><th>Tax paid</th><th>Population</th>
</tr></thead>
<tbody>
{% for place in places %}
<tr>
<td><a href="{{ place.get_absolute_url }}">{{ place.vill }}</a></td>
<td>{{ place.raw_value|floatformat:"-1" }}</td>
<td>{{ place.population|floatformat:"-1" }}</td>
</tr>
{% endfor %}
</tbody>
</table>

</div>

<script type="text/javascript">
{% if centre %}
    var lat = {{centre.y}};
    var lng = {{centre.x}};
{% else %}
    var lat = null;
	var lng = null;
{% endif %}
window.onload = set_up_map(lat, lng);
//var bounds = new google.maps.LatLngBounds();
{% for place in hundred.place_set.all %}
addMarker('{{place.location.y}}', '{{place.location.x}}', '{{place.grid}}', '{{place.vill}}', '{{place.vill_slug}}', '{{place.hundred}}', '{% for county in place.county.all %}{{ county }} {% endfor %}', '{{place.population|floatformat:"-1"}}');
//var latlng = new google.maps.LatLng({{place.location.y}}, {{place.location.x}});
//bounds.extend(latlng);
{% endfor %}
//var fitmap = new google.maps.Map(document.getElementById("map_canvas"));
//fitmap.fitBounds(bounds);
//alert(bounds);
</script>

{% endblock %}

templates/domes/map.html
{% extends "domes/base.html" %}

{% block title %}Map {% endblock %}
{% block description %}Complete map of all places listed in Domesday Book{% endblock %}
{% block nav-class %}nav-places{% endblock %}
{% block content %}

<div class="page_title">
<h1>Map of Domesday Book</h1> 

<p>The whole of England, as mapped in Domesday Book. This may take some time to load!</p>
</div>

<div class="content">

<div id="map_canvas" style="width: 100%; height: 700px"></div>
</div>

<div style="clear: both;"></div>

<script type="text/javascript"> 
function whole_map() {
	var center = new google.maps.LatLng(52.36187505907603, -1.614990234375);
	var options = {
	  'zoom': 7,
	  scrollwheel: false,
	  'center': center,
	  'mapTypeId': google.maps.MapTypeId.ROADMAP
	};
    var markers = [];
	var map = new google.maps.Map(document.getElementById("map_canvas"), options);
    {% for place in places %}
		var latlng = new google.maps.LatLng({{ place.location.y }}, {{place.location.x}});
		markers.push(new google.maps.Marker({'position': latlng}));
		// var map_marker = createMarker({{ place.location.y }}, {{ place.location.x }}, {{ place.grid }}, 
		// 			                   {{ place.vill }}, {{ place.vill_slug }}, {{ place.hundred }}, 
		// 		                       'Staffordshire', {{ place.population }});
		markers.push(map_marker);
    {% endfor %}
	var mc = new MarkerClusterer(map,markers);
}
window.onload = whole_map();
</script>

{% endblock %}